import { Router } from "express";
import type { Request, Response } from "express";
import { CHANGELOG_LATEST_VERSION, compareVersions } from "@ticket/shared";
import type { ChangelogStatusResponse } from "@ticket/shared";
import { prisma } from "../db";
import { requireAuth, sessionOf } from "../middleware/auth";

/**
 * The "what's new" changelog (issue #94): whether the caller has unseen
 * entries, and marking the latest one seen.
 *
 * `requireAuth` throughout, same reasoning as `new-features.ts` next to it: no
 * admin-editable half here either — the content itself lives in
 * `CHANGELOG_ENTRIES` (`@ticket/shared`), generated by CI, not written
 * through this API.
 */

export const changelogRouter = Router();

changelogRouter.get(
  "/status",
  requireAuth,
  async (_req: Request, res: Response<ChangelogStatusResponse>) => {
    // Nothing recorded yet: stay quiet, same as a tutorial page with no
    // authored content — see `defaultContent` in tutorials.ts.
    if (CHANGELOG_LATEST_VERSION === null) {
      res.json({ shouldShow: false });
      return;
    }

    const session = sessionOf(res);

    const row = await prisma.changelogSeen.findUnique({
      where: { userId: session.user.id },
      select: { seenVersion: true },
    });

    const shouldShow =
      !row || compareVersions(row.seenVersion, CHANGELOG_LATEST_VERSION) < 0;

    res.json({ shouldShow });
  },
);

/**
 * Mark the *current* latest entry seen for the caller. Upsert, same reason as
 * the tutorial's and the "new" badge's `/seen`: no row exists on a user's
 * first open, and always writing `CHANGELOG_LATEST_VERSION` as of this moment
 * means an entry landing between the status read and this write is still
 * honoured — the caller just saw whatever was current when they opened it.
 *
 * Takes no body: the version written is the server's own constant, never a
 * client-supplied one, so a caller cannot mark seen a version it never saw.
 */
changelogRouter.post(
  "/seen",
  requireAuth,
  async (_req: Request, res: Response<{ ok: true } | { error: string }>) => {
    if (CHANGELOG_LATEST_VERSION === null) {
      res.status(404).json({ error: "No changelog entries yet" });
      return;
    }

    const session = sessionOf(res);
    const seenVersion = CHANGELOG_LATEST_VERSION;

    await prisma.changelogSeen.upsert({
      where: { userId: session.user.id },
      create: { userId: session.user.id, seenVersion },
      update: { seenVersion, seenAt: new Date() },
    });

    res.json({ ok: true });
  },
);
